apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template: helm install backend-app ./helm-charts/backend-chart

    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fatma467/backend-app:latest
          ports:
            - containerPort: 3001
